# iOS CircleCI configuration file
#
version: 2.1

defaults: &defaults
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: /Users/distiller/project/output
    shell: /bin/bash --login -o pipefail

commands:

  # Sets Ruby version and installs all gems, using a cache
  setup_ruby:
    steps:
      - run:
          name: Set Ruby version
          command: echo "ruby-2.6" > ~/.ruby-version
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
      - run:
          name: Install dependencies in Gemfile
          command: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  
  # Installs utilities from Homebrew, and gems from the Gemfile
  install_dependencies:
    steps:
      - setup_ruby

  # Runs `pod update`
  pod_update:
    parameters:
      swift:
        type: string
        default: '5.0'
    steps:
      - run:
          name: Set Swift language version
          command: echo "<< parameters.swift >>" > Example/.swift-version
      - run:
          name: Pod Update
          command: |
            cd Example && bundle exec pod update

  # Build the Example app & run the tests
  build:
    steps:
      - run:
          name: Build and run tests
          command: fastlane scan --workspace "Example/Lasso.xcworkspace"
          #command: fastlane scan --workspace "Example/Lasso.xcworkspace" --code_coverage --output_directory output/scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: Lasso-Example
  
  # Build the SwiftPM Example app & run the tests
  build_swiftpm:
    steps:
      - run:
          name: Build and run tests
          command: >-
            xcodebuild build
            -project "Example/SwiftPM/Lasso-SwiftPM/Lasso-SwiftPM.xcodeproj"
            -scheme "Lasso-SwiftPM"
            -destination "platform=iOS Simulator,name=iPhone 11"

jobs:

  build-gem-cache:
    <<: *defaults
    macos:
      xcode: 10.3.0
    steps:
      - checkout
      - setup_ruby

  build-and-test-swift42:
    <<: *defaults
    parallelism: 4
    macos:
      xcode: 10.3.0
    steps:
      - checkout
      - install_dependencies
      - pod_update:
          swift: '4.2'
      - build

  build-and-test-swift5:
    <<: *defaults
    parallelism: 6
    macos:
      xcode: 10.3.0
    steps:
      - checkout
      - install_dependencies
      - pod_update:
          swift: '5.0'
      - build

  build-and-test-swift51:
    <<: *defaults
    parallelism: 6
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - install_dependencies
      - pod_update:
          swift: '5.1'
      - build

  build-and-test-swift52:
    <<: *defaults
    parallelism: 6
    macos:
      xcode: 11.4.0
    steps:
      - checkout
      - install_dependencies
      - pod_update:
          swift: '5.2'
      - build

  build-and-test-swiftpm:
    <<: *defaults
    parallelism: 6
    macos:
      xcode: 11.4.0
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - install_dependencies
      - build_swiftpm

workflows:
  version: 2

  build-test:
    jobs:
      - build-gem-cache
      - build-and-test-swift42:
          requires:
            - build-gem-cache
      - build-and-test-swift5:
          requires:
            - build-gem-cache
      - build-and-test-swift51:
          requires:
            - build-gem-cache
      - build-and-test-swift52:
          requires:
            - build-gem-cache
      - build-and-test-swiftpm:
          requires:
            - build-gem-cache
